### ISSUE TITLE
No right arrow to progress on Module from STEP 1 to STEP 2 - FIX

### ISSUE THREAD

**Issue by why-science** [why-science/demo#14]
![image](https://user-images.githubusercontent.com/70287522/173660639-987eeeb5-0467-4f1c-b240-58231074d99a.png)

**Comment by rajthilak87** [comment]
FIXED

Step 1 :
![image](https://user-images.githubusercontent.com/89064511/173840520-354c3476-e93a-4a6e-988b-a404edf23ee6.png)

Step 2:
![image](https://user-images.githubusercontent.com/89064511/173840688-ec7c273f-20b7-41c6-b4d8-d349face8ec1.png)

**Comment by why-science** [comment]
Not fixed for me as user akpaly@gmail.com -  need to remove copies of the summative assessments I have completed on the system.
![image](https://user-images.githubusercontent.com/70287522/173864023-92e6550e-c723-418b-83ec-1c9482b3a258.png)

**Comment by why-science** [comment]
Got it it is fixed. Coach needs to add instructor for this to work. Thanks
